name: Build Main
permissions:
  contents: read
on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        tc: [ 17, 21, 25 ]
    runs-on: ubuntu-latest
    env:
      BUILD_EVENT: ${{ github.event_name }}
      TARGET_COMPATIBILITY: ${{ matrix.tc }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          gradle-version: current
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build and Test
        run: chmod +x gradlew && ./gradlew clean test jacocoTestReport
      - name: Verify Javadoc
        run: ./gradlew javadoc
      - name: Send coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          parallel: true
          flag-name: tc${{ matrix.tc }}
      - name: Publish Snapshot
        run: ./gradlew -i publishToSonatype

  coveralls-finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finish
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          parallel-finished: true
          carryforward: "tc17"